/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    SimpleStencil: typeof import('./src/components/Stencil/SimpleStencil.vue')['default']
    Stencil: typeof import('./src/components/Stencil/Stencil.vue')['default']
    TaskNode: typeof import('./src/components/TaskNode/index.vue')['default']
    VGraph: typeof import('./src/components/VGraph.vue')['default']
    Zoom: typeof import('./src/components/Zoom.vue')['default']
  }
}
